services:
  log-reader:
    build: ./log-reader
    volumes:
      - ./log-reader:/app
    networks:
      - log-network
    restart: unless-stopped
    depends_on:
      - rsyslog
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

  rsyslog:
    build: ./rsyslog
    volumes:
      - ./logs:/sb/logs
      - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
    ports:
      - "5514:5514/udp"
      - "5514:5514/tcp"
    networks:
      - log-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "rsyslogd"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - ./logs:/sb/logs
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    ports:
      - "9080:9080"
    networks:
      - log-network
    restart: unless-stopped
    depends_on:
      - loki
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9080/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

  loki:
    build: ./loki
    volumes:
      - ./logs:/sb/logs
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
      - loki-data:/loki
      - loki-wal:/wal
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    networks:
      - log-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M

  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "3000:3000"
    networks:
      - log-network
    depends_on:
      - loki
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  log-network:
    driver: bridge

volumes:
  loki-data:
    driver: local
  loki-wal:
    driver: local
  grafana-data:
    driver: local
