services:
  log-reader:
    build: ./log-reader
    volumes:
      - ./log-reader:/app
    networks:
      - log-network

  rsyslog:
    build: ./rsyslog
    volumes:
      - ./logs:/sb/logs
      - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf
    ports:
      - "5514:5514/udp"
      - "5514:5514/tcp"
    networks:
      - log-network

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - ./logs:/sb/logs
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    ports:
      - "9080:9080"
    networks:
      - log-network

  loki:
    build: ./loki
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
      - loki-data:/loki
      - loki-wal:/wal
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    networks:
      - log-network

  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "3000:3000"
    networks:
      - log-network
    depends_on:
      - loki

networks:
  log-network:
    driver: bridge

volumes:
  loki-data:
    driver: local
  loki-wal:
    driver: local
  grafana-data:
    driver: local
