server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: traffic_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: traffic_logs
          __path__: /sb/logs/incoming/traffic_only/**/*.log
          log_type: TRAFFIC
